// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjlqUdrfvBz2ULEIaLvtShcIqKx56bgi0',
    appId: '1:771399540510:web:8f6292c5f5f0f91559730f',
    messagingSenderId: '771399540510',
    projectId: 'absence-app-633e1',
    authDomain: 'absence-app-633e1.firebaseapp.com',
    storageBucket: 'absence-app-633e1.firebasestorage.app',
    measurementId: 'G-T1D4PEN23R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA9OP_0iY2Dl9W4tB-l57jr0uNxCqyh1I',
    appId: '1:771399540510:android:4106b19d3095634f59730f',
    messagingSenderId: '771399540510',
    projectId: 'absence-app-633e1',
    storageBucket: 'absence-app-633e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUWd8LTIh3-vf6HffvrgwvNbUzZMXbHF8',
    appId: '1:771399540510:ios:b124dbb871f5910759730f',
    messagingSenderId: '771399540510',
    projectId: 'absence-app-633e1',
    storageBucket: 'absence-app-633e1.firebasestorage.app',
    androidClientId: '771399540510-cl0v588jmms16e8ac5omk5utp6hlrdg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.summerSchoolApp',
  );

}